### ISSUE TITLE
Decentralize configurable events in multiple configurations

### ISSUE THREAD

**Issue by MarvinKlar** [Ajneb97/ConditionalEvents#1]
I would like to be able to configure the events in multiple configuration files instead of having ALL events in the `config.yml` I thought about a folder (`plugins/ConditionalEvents/events`) where you can place any `<configXYZ>.yml`, which will be loaded the same way the `plugins/ConditionalEvents/config.yml` gets loaded. So you would be able to categorize the events you create and to keep the files small and maintainable.

Is this idea acceptable? If so, I would love to implement this feature to ConditionalEvents!

Thanks and regards!

**Comment by Ajneb97** [comment]
This will be implemented in future updates!
