### ISSUE TITLE
[BUG] JUMP_BOOST does not work in give_potion_effect 

### ISSUE THREAD

**Issue by Ucyanwind** [Ajneb97/ConditionalEvents#104]
I get an error when I use JUMP_BOOST in give_potion_effect, but it works fine when I use other potion effects like SPEED.The game version is 1.20.1.
![image](https://github.com/user-attachments/assets/8aec2e17-9d34-46d2-8c27-0ebb2587f7d6)
![image](https://github.com/user-attachments/assets/8b196ec9-cd41-4f8b-ae2d-b651c2516c72)

**Comment by Ajneb97** [comment]
In your version, that effect is called JUMP:
https://helpch.at/docs/1.20/org/bukkit/potion/PotionEffectType.html#JUMP

**Comment by Ucyanwind** [comment]
THANKS^^
