### ISSUE TITLE
Suggestion: variable to check if player under the sky

### ISSUE THREAD

**Issue by Fenix5fire** [Ajneb97/ConditionalEvents#12]
It's very hard to check if there is no blocks between player and the sky.

It's possible to get it by checking every single block for air above the player or by using Block method [getLightFromSky](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/block/Block.html#getLightFromSky())(), but to use it in repetitive event you need to use Spigot's [PlayerMoveEvent](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/player/PlayerMoveEvent.html) which gonna be executed 20 times per second which is a lot.

This variable could be useable for checking if player is under the clear sky or if he actually affected by rain and possibly different uses

**Comment by Jonhy188** [comment]
yes, it would be a very useful variable.

**Comment by Jonhy188** [comment]
I only found the variable %player_block_underneath% for the block below the player, but I didn't find one that tells you which block is above the player.

**Comment by Ajneb97** [comment]
Added in the latest version.
