### ISSUE TITLE
Suggestion: New operator AND, && 

### ISSUE THREAD

**Issue by Reeferx7** [Ajneb97/ConditionalEvents#13]
Hello, is possible to add "AND" operator to compare conditions in same line with different execute actions.

A small example:

    - '%item% == IRON_SWORD AND %block% !contains GRASS execute action1' Result true or false

    - '%item% == DIAMOND_SWORD && %block% !contains GRASS execute actions2'

**Comment by Ajneb97** [comment]
The AND operator is accomplished adding another condition line
