### ISSUE TITLE
Memory Allocation

### ISSUE THREAD

**Issue by LucidAPs** [Ajneb97/ConditionalEvents#14]
The item_interact event is allocating a lot of memory.
https://spark.lucko.me/05pLHwyAsQ

**Comment by Ajneb97** [comment]
How many item_interact and block_interact events do you have? It seems the memory issue is caused by the MathUtils.calculate() method, which tries to parse formulas in conditions.

**Comment by LucidAPs** [comment]
> 

These are all the item_interact events I am using
https://nekobin.com/miwuzoyefe

**Comment by Ajneb97** [comment]
Ok I will check it on my server

**Comment by Ajneb97** [comment]
This should be fixed now.
