### ISSUE TITLE
Feature Request: Ability to issue an action to players that are within the worldguard region.

### ISSUE THREAD

**Issue by AshiroKun** [Ajneb97/ConditionalEvents#15]
Hey,

I got a pretty useful idea that would be appreciated if it added.

Currently you can only use "To Actions" types for limited things. Sometimes the Range method does not work like intended.

Therefore, it would be a better option if there was a "to region" action type that checks a player in the region and anybody in that region will be given the commands if they meet the condition as per usual.

**Comment by Ajneb97** [comment]
You can currently do that by using the "to_condition" action, to check for all players on the server if they accomplishes some conditions and execute the actions for all of them.
