### ISSUE TITLE
Open Inventory Error

### ISSUE THREAD

**Issue by Nic0las-Ponce** [Ajneb97/ConditionalEvents#16]
Idk if its a bug or im doing something wrong, I want to trigger an event when a player open his inventory (the one with 4x4 crafting space). I checked it spigot inventory types and apparently its called CRAFTING, but it doesnt work. Also, I tryed using the debug, inventorys like chest and workbenchs are checked for the condition but player inventory does not. Maybe it has to do with aternos or cracked minecraft?

Saludos desde Argentina, sos un genio.

**Comment by Nic0las-Ponce** [comment]
I see... Do you know any other way to do it? I'm trying to recreate the old advancement of opening the player inventory

**Comment by Ajneb97** [comment]
Saddly I don't know if this is possible :/
