### ISSUE TITLE
Default /discord event

### ISSUE THREAD

**Issue by Vankka** [Ajneb97/ConditionalEvents#22]
Hi,

I'm one of the developers of DiscordSRV, and recently a lot of users have have been coming into our Discord server asking about the `/discord` command returning the output that [ConditionalEvents provides](https://github.com/Ajneb97/ConditionalEvents/blob/a2312915d9cdca56864fe2a74fca871348cfa884/src/main/resources/events/more_events.yml#L2) (instead of DiscordSRV's own handling).

I would like to ask if it's possible to disable the alias you have by default (for example by putting it in comment), or change the example to another command like `/website` instead. As most users don't know that the alias is coming from ConditionalEvents, they end up confused and come to us for help.

**Comment by Ajneb97** [comment]
Ok, don't worry. I will change the default example on a future update!
