### ISSUE TITLE
Suggestion: IP CONDITION

### ISSUE THREAD

**Issue by Zapry** [Ajneb97/ConditionalEvents#24]
Hola tengo una sugerencia. Me gustaria que se pueda poner una condicion la cual sea referente a la IP del usuario. Para explicarlo dare un ejemplo. 

Tengo pensado con conditionalevents crear un evento el cual se llame "LlavesGratis". En este, poner un comando el cual sea /freekeys y que el servidor te de automáticamente unas llaves. Mi idea, seria crear una condición la cual solamente te deje ejecutar ese comando 2 veces por IP. Es decir, Un usuario entra con la cuenta llamada "A" usa el comando /freekeys y le da las recompensas. Luego este usuario entra con una cuenta llamada "B", usa el comando y el servidor le da las keys correspondientes. Pero, el usuario al entrar a la cuenta "C", si quiere usar ese comando no le deje y le salga un mensaje de error diciendo "Ya haz reclamado 2 veces esta recompensa (Osea el plugin detecto que su IP ejecuto el comando 2 veces)

**Comment by Ajneb97** [comment]
PlaceholderAPI ya provee esa variable: %player_ip%
https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders
