### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by KhrysAK47** [Ajneb97/ConditionalEvents#32]
FIREWORK_SPARK is not recognized as a particle in Spigot 1.17.1 in the plugin, however, it is an available effect

      - 'particle: effect:FIREWORK_SPARK offset:0.8;1;0.8 speed:1 amount:10'

**Comment by Ajneb97** [comment]
https://helpch.at/docs/1.17/org/bukkit/Particle.html
It seems the particle is FIREWORKS_SPARK. You missed an "S".
