### ISSUE TITLE
Duda: Acciones determinadas para varios jugadores

### ISSUE THREAD

**Issue by Pachecon22** [Ajneb97/ConditionalEvents#34]
Muy buenas me gustaría saber si se puede hacer que las acciones "Play Sound" y "Title" afectarán a todo el servidor en vez de a solo 1 jugador.

Ejemplo: crear un evento en el que si un jugador tiene op, cuando se una al servidor, que a todos los conectados les ponga en la pantalla "Ha entrado un ADMIN" y sonara algún sonido

**Comment by Ajneb97** [comment]
Ya puedes hacer eso con la acción de to_all:
https://ajneb97.gitbook.io/conditionalevents/actions/to-actions
