### ISSUE TITLE
Add a feature actions summon

### ISSUE THREAD

**Issue by JuraRusan** [Ajneb97/ConditionalEvents#39]
Hello, I would like to ask you to add a feature so that you can summon mobs.

For example, I use `set_block` and it is very great that it does not leave logs in the console, but this type of `summon` is very much missing, so I have to use `console_command: summon snow_golem ...` which is also good, but not what is expected.

Thank you in advance!

**Comment by Ajneb97** [comment]
I will take it into consideration

**Comment by JuraRusan** [comment]
@Ajneb97  Thanks a lot for adding the feature
