### ISSUE TITLE
player_chat, player_join and player_leave don't update unless /ce reload

### ISSUE THREAD

**Issue by KhrysAK47** [Ajneb97/ConditionalEvents#54]
None of those events work properly unless done /ce reload after a server restart. 

https://pastebin.com/pvi8NvL2

**Comment by KhrysAK47** [comment]
Running Paper 1.20.4

**Comment by Ajneb97** [comment]
How are you restarting your server?

**Comment by KhrysAK47** [comment]
Normal server restart, not /reload

**Comment by Ajneb97** [comment]
I will fix this in the next update
