### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by XionioXMaster** [Ajneb97/ConditionalEvents#7]
Events:
  event4:
    type: block_break
    conditions:
    - '%block% != STONE'
    actions:
      default:
      - 'cancel_event: true'
      - 'message: &cNo rompas solo tapalo de antorchas'
      - 'playsound: BLOCK_NOTE_BLOCK_PLING;10;0.1'
      
      Console
      https://mcpaste.com/6e5a1a468055fc20f0d578a03a1bbc01

**Comment by Ajneb97** [comment]
Descarga la última version del plugin

**Comment by XionioXMaster** [comment]
> Скачать последнюю версию плагина

This last
