### ISSUE TITLE
Could not pass event RegionEnteredEvent to ConditionalEvents v4.52.1

### ISSUE THREAD

**Issue by baailey** [Ajneb97/ConditionalEvents#70]
13.06 21:45:22 [Server] ERROR Could not pass event RegionEnteredEvent to ConditionalEvents v4.52.1
13.06 21:45:22 [Server] INFO java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
13.06 21:45:22 [Server] INFO at ConditionalEvents (2).jar/ce.ajneb97.utils.ItemUtils.getItemFromProperties(ItemUtils.java:139) ~[ConditionalEvents (2).jar:?]
13.06 21:45:22 [Server] INFO at ConditionalEvents (2).jar/ce.ajneb97.utils.ActionUtils.giveItem(ActionUtils.java:330) ~[ConditionalEvents (2).jar:?]
13.06 21:45:22 [Server] INFO at ConditionalEvents (2).jar/ce.ajneb97.model.internal.ExecutedEvent.executeAction(ExecutedEvent.java:377) ~[ConditionalEvents (2).jar:?]
13.06 21:45:22 [Server] INFO at ConditionalEvents (2).jar/ce.ajneb97.model.internal.ExecutedEvent.executeActionsFinal(ExecutedEvent.java:206) ~[ConditionalEvents (2).jar:?]
13.06 21:45:22 [Server] INFO at ConditionalEvents (2).jar/ce.ajneb97.model.internal.ExecutedEvent.executeActions(ExecutedEvent.java:98) ~[ConditionalEvents (2).jar:?]
13.06 21:45:22 [Server] INFO at ConditionalEvents (2).jar/ce.ajneb97.managers.EventsManager.checkSingularEvent(EventsManager.java:133) ~[ConditionalEvents (2).jar:?]
13.06 21:45:22 [Server] INFO at ConditionalEvents (2).jar/ce.ajneb97.managers.EventsManager.checkEvent(EventsManager.java:48) ~[ConditionalEvents (2).jar:?]
13.06 21:45:22 [Server] INFO at ConditionalEvents (2).jar/ce.ajneb97.model.internal.ConditionEvent.checkEvent(ConditionEvent.java:77) ~[ConditionalEvents (2).jar:?]
13.06 21:45:22 [Server] INFO at ConditionalEvents (2).jar/ce.ajneb97.listeners.dependencies.WGRegionEventsListener.onRegionEnter(WGRegionEventsListener.java:28) ~[ConditionalEvents (2).jar:?]
13.06 21:45:22 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor880.execute(Unknown Source) ~[?:?]
13.06 21:45:22 [Server] INFO at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
13.06 21:45:22 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:1.20.6-137-bd5867a]
13.06 21:45:22 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
13.06 21:45:22 [Server] INFO at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
13.06 21:45:22 [Server] INFO at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
13.06 21:45:22 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:627) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
13.06 21:45:22 [Server] INFO at WorldGuardEvents-1.18.1.jar/net.raidstone.wgevents.Entry.onCrossBoundary(Entry.java:56) ~[WorldGuardEvents-1.18.1.jar:?]
13.06 21:45:22 [Server] INFO at worldguard-bukkit-7.0.10-SNAPSHOT-dist (1).jar/com.sk89q.worldguard.session.Session.testMoveTo(Session.java:235) ~[worldguard-bukkit-7.0.10-SNAPSHOT-dist (1).jar:?]
13.06 21:45:22 [Server] INFO at worldguard-bukkit-7.0.10-SNAPSHOT-dist (1).jar/com.sk89q.worldguard.session.Session.testMoveTo(Session.java:195) ~[worldguard-bukkit-7.0.10-SNAPSHOT-dist (1).jar:?]
13.06 21:45:22 [Server] INFO at worldguard-bukkit-7.0.10-SNAPSHOT-dist (1).jar/com.sk89q.worldguard.bukkit.listener.PlayerMoveListener.onPlayerMove(PlayerMoveListener.java:100) ~[worldguard-bukkit-7.0.10-SNAPSHOT-dist (1).jar:?]
13.06 21:45:22 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor136.execute(Unknown Source) ~[?:?]
13.06 21:45:22 [Server] INFO at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
13.06 21:45:22 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:1.20.6-137-bd5867a]
13.06 21:45:22 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
13.06 21:45:22 [Server] INFO at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
13.06 21:45:22 [Server] INFO at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
13.06 21:45:22 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:627) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
13.06 21:45:22 [Server] INFO at net.minecraft.server.network.ServerGamePacketListenerImpl.handleMovePlayer(ServerGamePacketListenerImpl.java:1567) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
13.06 21:45:22 [Server] INFO at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket.handle(ServerboundMovePlayerPacket.java:34) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
13.06 21:45:22 [Server] INFO at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket$PosRot.handle(ServerboundMovePlayerPacket.java:105) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
13.06 21:45:22 [Server] INFO at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:55) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
13.06 21:45:22 [Server] INFO at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
13.06 21:45:22 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
13.06 21:45:22 [Server] INFO at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
13.06 21:45:22 [Server] INFO at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1511) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
13.06 21:45:22 [Server] INFO at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:195) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
13.06 21:45:22 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
13.06 21:45:22 [Server] INFO at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1488) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
13.06 21:45:22 [Server] INFO at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1411) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
13.06 21:45:22 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
13.06 21:45:22 [Server] INFO at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1377) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
13.06 21:45:22 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1238) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
13.06 21:45:22 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
13.06 21:45:22 [Server] INFO at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

Event that triggered the error:
```
  skywarsblue:
    type: wgevents_region_enter
    conditions:
    - '%region% == skywarsblue'
    actions:
      default:
      - 'give_item: id:light_blue_banner;amount:1;name:&b&lBlue Team;lore:&9&lSky Servers Skywars;slot:HELMET;enchants:BINDING_CURSE'
      - 'console_command: tppos %player% -234.5 108 -669.5 -0 0 events'
```

**Comment by Ajneb97** [comment]
You are not using the enchants property of give_item correctly:
https://ajneb97.gitbook.io/conditionalevents/actions#give-item

You must use this format:
enchants:<enchant1>-<level1>|<enchantN>-<levelN>
