### ISSUE TITLE
Problema al usar la comilla simple ( ' )

### ISSUE THREAD

**Issue by Turromantik** [Ajneb97/ConditionalEvents#72]
Hola Ajneb y todos, buenos días. Usando tu plugin me encontré con un problema al cual no le pude encontrar solución.

     Contexto de lo que quería hacer: Al hacer clic en una cama, me aparezca un texto personalizado en forma de "entity tag" arriba de la misma.
![image](https://github.com/Ajneb97/ConditionalEvents/assets/140079854/2f81c5f0-0eeb-4b09-96ac-55fd7a769269)
El problema radica en la personalización del texto. Esto causado por no poder usar las comillas simples dentro del comando. 
     Como veras en la foto de abajo, para que correctamente se pueda modificar el texto (y que no aparezca "soporte para armaduras"), requiere el uso de comillas simples, y el plugin al utilizar este recurso como "main" o propio, no permite que las pueda usar dentro del comando (te remarque la parte especifica que usa las comillas, y te lo compare con los renglones de abajo que no las tienen (el primer renglón rompe el evento/acción, los demás son aceptados, pero sin modificar el texto)
![image](https://github.com/Ajneb97/ConditionalEvents/assets/140079854/3ab8514e-07f5-4776-9091-b0427a8f0d96)

Solución que propongo: agregar un símbolo especifico ubicado justo delante de la comilla simple, que inhabilite que el plugin tome en cuenta esa comilla simple. Un ejemplo seria +' 

Aunque ahora que lo pienso... eso no solucionaria nada ya que al agregar un signo de más, se rompe el comando de minecraft y no se podra utilizar :(

Adelantando, gracias por leerme e invito a todos a opinar sobre el tema. Ya que capaz haya otra solución que no implique modificar el plugin.

PD... Hermoso recurso creaste muchas gracias, desde que lo conocí no paro de crear funcionalidades para mi server (que nacen de mi mente) y permite agregar este toque personal que tanto busco :)

**Comment by Ajneb97** [comment]
Eso es problema de los archivos YAML. Para que funcionen las comillas simples, el inicio y el final de la linea tienen que ser comillas dobles. Pero si lo haces asi, tienes que eliminar las comillas dobles que esten dentro de la linea. Ej:

- "console_command: {CustomName:'{'text':'hola'}'}"

**Comment by Turromantik** [comment]
Gracias por la respuesta!
No tenia esa información que se podía utilizar las comillas dobles para permitir las comillas simples.
Por desgracia... El problema continua, ahora invirtiendose jajaj. Ahora al no poder utilizar las comillas dobles, el comando se rompe nuevamente y no funciona. Mañana dare por cerrado este issue, nuevamente gracias <3

**Comment by Turromantik** [comment]
¡ChatGPT salvando las papas!
![image](https://github.com/Ajneb97/ConditionalEvents/assets/140079854/c7a003c9-f27e-4dc4-a6cd-9d80df19b0e6)
Agrego una barra invertida antes de las comillas dobles, y asi se permite el uso de las mismas dentro del comando y dentro de la accion.
![image](https://github.com/Ajneb97/ConditionalEvents/assets/140079854/b8ff9bc6-0ad9-4b7f-8a24-e20c3c13e0b4)
Graciasss, estoy contento, cierro el issue saludos!
