### ISSUE TITLE
Bug on repetitive events

### ISSUE THREAD

**Issue by OMarcoGPO** [Ajneb97/ConditionalEvents#76]
![image](https://github.com/user-attachments/assets/064c90fc-e88a-4694-a98f-2066fe624521)
Español:
Este bug creo que no se ha solucionado correctamente, estoy en la 1.20.4 usando la última versión del plugin. Tengo un evento repetitivo que debería ejecutarse a cada segundo (20 ticks), y se ve a simple vista que va mucho más rápido, además, no puedo desactivarlo, demostrando así que posiblemente este duplicado. No se que aportar puesto que no es un error en consola.
English:
I think this bug has not been solved correctly, I am on 1.20.4 using the latest version of the plugin. I have a repeating event that should be executed every second (20 ticks), and it can be seen at first glance that it goes much faster, in addition, I cannot deactivate it, thus showing that it is possibly duplicated. I don't know what to contribute since it is not an error in the console.

**Comment by Ajneb97** [comment]
Este bug solamente ocurria cuando estas usando algun plugin que implemente la API de ConditionalEvents. Mandame tu evento. Y para estar seguro de que se esta repitiendo usa /ce debug

**Comment by OMarcoGPO** [comment]
Este es mi evento, un simple repetitive_server. Ya hice anteriormente lo del /ce debug, y pues se vio como se repite muchísimas veces el evento aunque sea a cada segundo la repetición. 

También aclarar que no solo es este único evento, pues todos los que sean repetitive_server (quizás repetitive de cada jugador, no te lo confirmo), se están repitiendo más rápidamente y no puedo desactivarlos.

Por último te confirmo que este evento y lo otros funcionaban de la manera adecuada en la versión anterior a la última del plugin.

Muchas gracias por tu rápida respuesta anteriormente y espero que todo esto te sirva.

Cooldown_epoca:
    type: repetitive_server
    repetitive_time: 20
    conditions:
    - '%servervariables_globalvalue_epoca_cooldown% == 0 execute done'
    actions:
      default:
      - 'console_command: svar reduce epoca_cooldown 1 silent:true'
      done:
      - 'console_command: svar set epoca_cooldown 16 silent:true'
      - 'to_all: message: &5&lOrigins&d&lCraft &8| &aLa época está cambiando...'
      - 'console_command: execute as @a at @s run playsound minecraft:item.trident.thunder
        ambient @s ~ ~ ~ 20 0.65'
      - 'wait_ticks: 45'
      - 'call_event: change_epoca;%r%=%random_1_23%'

**Comment by OMarcoGPO** [comment]
Por algún motivo el bug me ocurrió solo una vez, y no conseguí reproducirlo, si me ocurre de nuevo abriré el bug otra vez
