### ISSUE TITLE
Feature request | Add money

### ISSUE THREAD

**Issue by Rexmen1** [Ajneb97/ConditionalEvents#77]
with current method where i use command to give money to players for some custom events its heavy and spams console with this warning...

[15:53:55] [Server thread/INFO]: Reapeating command detected while performing specialized command (cmi money give Rairah 13.5 -s)
[15:53:55] [Server thread/INFO]: Infinite loop detected! Please update your commands relating to (cmi money give Rairah 13.5 -s)

so if there is add_money action which will help alot i think... Ty

**Comment by Rexmen1** [comment]
sharing config here please tell me whats wrong here
[

](https://ptero.co/cemiboboba.less)

**Comment by Rexmen1** [comment]
issue here is that players mine alot and with eff 5 + haste 2 its even faster

**Comment by Rexmen1** [comment]
and isn't vault is the only thing needed to add support for adding money?

**Comment by Ajneb97** [comment]
Yes, but some plugins don't use Vault anymore since it is not updated since 2020.

**Comment by Rexmen1** [comment]
You didn't said whats wrong with that config... You said something is wrong with setup so please guide me

https://ptero.co/cemiboboba.less

**Comment by Ajneb97** [comment]
If you are talking about the last event, I don't see anything wrong. Try adding a cooldown to the event.

**Comment by Rexmen1** [comment]
thats what im saying there is nothing wrong with config and still gives me error 
[15:53:55] [Server thread/INFO]: Reapeating command detected while performing specialized command (cmi money give Rairah 13.5 -s)
i guess gonna use some other plugin for it bcz adding cooldown isn't possible for what I'm trying to setup for it..

**Comment by Rexmen1** [comment]
Bye, can close it i guess?
