### ISSUE TITLE
Problema con la acción execute_action_group

### ISSUE THREAD

**Issue by OMarcoGPO** [Ajneb97/ConditionalEvents#84]
La acción execute_action_group ha dejado de funcionar correctamente en las últimas versiones (no se en que versión exactamente ha ocurrido esto), ahora estoy ahora mismo en la versión 4.57.2 del plugin, y el funcionamiento es el siguiente:

Dado el siguiente código de ejemplo:
      - 'execute_action_group: action1:1;action2:1'
      
El plugin ejecutará siempre action1, siendo realmente un 50% de que se ejecute.

**Comment by Ajneb97** [comment]
Intenta poniendo las probabilidades en 50 ambas, si sigue sin funcionar intenta agregando un action3.

**Comment by OMarcoGPO** [comment]
Efectivamente, poniendo 50 y 50 funciona correctamente, muchas gracias
